In [1]:
import pandas as pd

In [2]:
import os

In [5]:
caminho_script = os.getcwd()

caminho_dados = os.path.join(caminho_script,'Dados_590')

In [7]:
for arquivo in os.listdir(caminho_dados):
    caminho_completo = os.path.join(caminho_dados, arquivo)
    if 'FULL' in arquivo:
        df_pd_full = pd.read_excel(caminho_completo)

In [9]:
df_pd_full.columns

Index(['DONOS', 'cidade_cliente', 'Status Etapa', 'transportador (grupo)',
       'uf_cliente', 'Vencimento Cliente', 'pedido_uuid', 'bairro_cliente',
       'barcode', 'cep_cliente', 'data_saida_cd', 'dt_status_etapa', 'idcarga',
       'nome_cliente', 'numero_nf', 'pedido_pacote', 'star', 'FINALIZADO',
       'EM ROTA', 'NÃO EM ROTA', 'INSUCESSO', 'AG.SAIDA CD', 'TOTAL'],
      dtype='object')

In [23]:
dado = df_pd_full[['numero_nf']]

In [12]:
df_pd_full.head(3)

,DONOS,cidade_cliente,Status Etapa,transportador (grupo),uf_cliente,Vencimento Cliente,pedido_uuid,bairro_cliente,barcode,cep_cliente,...,nome_cliente,numero_nf,pedido_pacote,star,FINALIZADO,EM ROTA,NÃO EM ROTA,INSUCESSO,AG.SAIDA CD,TOTAL
0,TODAS,ANAPOLIS,C/ transp - Em rota cliente,DOMICILIO GO,GO,VENCE HOJE,25cf5d52-eb6e-4d77-8494-d3246ada36d4,BOA VISTA,059000019160705475075250001001',75075250,...,GRANJA PENA REAL LTDA,11924-8,1526370105616149-1,Troca de transportadora,NaN,1.0,NaN,NaN,NaN,1
1,TODAS,TRINDADE,Finalizado,DOMICILIO GO,GO,VENCE HOJE,34934f87-228d-40dc-8c5a-19e65866f2f5,SETOR JARDIM IMPERIAL,059000019184214475391822001001',75391822,...,JORGE ALTINO DA SILVA,7660-06-01 00:00:00,1526370105597501-1,Saiu para entrega,1.0,NaN,NaN,NaN,NaN,1
2,TODAS,CIDADE OCIDENTAL,Finalizado,DOMICILIO GO,GO,VENCE HOJE,c6489766-8f9c-4ac5-b9c9-abb02a9805bf,MORADA DAS GARCAS,059000019160709072883640002002',72883640,...,ANA CAROLINA PEREIRA DA SILVA,18522-3,1526070105402506-1,NaN,1.0,NaN,NaN,NaN,NaN,1

In [14]:
df_pd_full = df_pd_full[['cidade_cliente','pedido_pacote', 'numero_nf']]

In [26]:
df_pd_full['numero_nf'] = pd.to_numeric(df_pd_full['numero_nf'], errors='coerce')

In [28]:
df_pd_full

           cidade_cliente       pedido_pacote  numero_nf
0                ANAPOLIS  1526370105616149-1        NaN
1                TRINDADE  1526370105597501-1        NaN
2        CIDADE OCIDENTAL  1526070105402506-1        NaN
3   AGUAS LINDAS DE GOIAS  1526370105602949-1        NaN
4   AGUAS LINDAS DE GOIAS  1526370105623400-1        NaN
5    APARECIDA DE GOIANIA  1526370105574922-2        NaN
6   AGUAS LINDAS DE GOIAS  1526370105588316-1        NaN
7     VALPARAISO DE GOIAS  1526470105633494-2        NaN
8          SENADOR CANEDO  1526370105555508-1        NaN
9                TRINDADE  1526370105571737-1        NaN
10   APARECIDA DE GOIANIA  1526370105574922-1        NaN
11                GOIANIA  1526470105663987-1        NaN
12                GOIANIA  1526470105650228-1        NaN